title: Welcome to my Blog
author: Rasvitha Rajendra
email: rasvithar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hope you enjoy!
# social links
github_username:  rasvithar # DO NOT include the @ character, or else the build will fail!
twitter_username: 
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
