title: Welcome to my Blog
author: Rasvitha Rajendra
email: rasvithar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hope you enjoy!
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  rasvithar # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme:minima
